version: "3.9"


services:
  mvc-php:
    hostname: php-fpm
    container_name: php-fpm
    build:
      context: .dockers/php-fpm
      dockerfile: Dockerfile

    volumes:
      - ./src/sandbox:/var/www/html
      #- ./src:/var/www/html
      - ./volumes/etc/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./volumes/etc/php/php.ini-dev:/usr/local/etc/php/php.ini




  mvc-nginx:
    hostname: mvc-nginx
    container_name: mvc-nginx
    build:
      context: .dockers/nginx
      dockerfile: Dockerfile

    ports:
      - "8080:80"

    volumes:
      - ./src/sandbox:/var/www/html
      #- ./src:/var/www/html
      - ./volumes/etc/nginx/nginx.conf:/etc/nginx.nginx.conf
      - ./volumes/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

